version: '3'
services:
  zoo1:
    build:
      context: .
      dockerfile: zoo.Dockerfile
    volumes:
      - ./data/zookeeper/1:/var/lib/zookeeper
      - ./conf/zookeeper/zoo.cfg:/usr/local/zookeeper/conf/zoo.cfg
    ports:
      - 2181:2181

  zoo2:
    build:
      context: .
      dockerfile: zoo.Dockerfile
    volumes:
      - ./data/zookeeper/2:/var/lib/zookeeper
      - ./conf/zookeeper/zoo.cfg:/usr/local/zookeeper/conf/zoo.cfg

  zoo3:
    build:
      context: .
      dockerfile: zoo.Dockerfile
    volumes:
      - ./data/zookeeper/3:/var/lib/zookeeper
      - ./conf/zookeeper/zoo.cfg:/usr/local/zookeeper/conf/zoo.cfg

  kafka1:
    build:
      context: .
      dockerfile: kafka.Dockerfile
    volumes:
      - ./conf/kafka/server.1.properties:/usr/local/kafka/config/server.properties
      - ./data/kafka/1:/tmp/kafka-logs
      - ./logs/kafka/1:/var/log/kafka
    ports:
      - 9092:9092
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  kafka2:
    build:
      context: .
      dockerfile: kafka.Dockerfile
    volumes:
      - ./conf/kafka/server.2.properties:/usr/local/kafka/config/server.properties
      - ./data/kafka/2:/tmp/kafka-logs
      - ./logs/kafka/2:/var/log/kafka
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  kafka3:
    build:
      context: .
      dockerfile: kafka.Dockerfile
    volumes:
      - ./conf/kafka/server.3.properties:/usr/local/kafka/config/server.properties
      - ./data/kafka/3:/tmp/kafka-logs
      - ./logs/kafka/3:/var/log/kafka
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  kafka4:
    build:
      context: .
      dockerfile: kafka.Dockerfile
    volumes:
      - ./conf/kafka/server.4.properties:/usr/local/kafka/config/server.properties
      - ./data/kafka/4:/tmp/kafka-logs
      - ./logs/kafka/4:/var/log/kafka
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  kafka5:
    build:
      context: .
      dockerfile: kafka.Dockerfile
    volumes:
      - ./conf/kafka/server.5.properties:/usr/local/kafka/config/server.properties
      - ./data/kafka/5:/tmp/kafka-logs
      - ./logs/kafka/5:/var/log/kafka
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  apps:
    build:
      context: .
      dockerfile: apps.Dockerfile
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - kafka4
      - kafka5

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    volumes:
      - ./client/src:/home/py/client/src
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - kafka4
      - kafka5

  faust:
    build:
      context: .
      dockerfile: faust.Dockerfile
    volumes:
      - ./faust:/home/faust
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - kafka4
      - kafka5
